### ISSUE TITLE
GDP Results TEXT

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/how-to-gdp#20]
Add text for this section. See https://github.com/USGS-VIZLAB/how-to-gdp/blob/master/data/page_text.yaml.

**Comment by dblodgett-usgs** [comment]
Here's a start:

These precipitation data could now be used in a watershed model, data visualization, or statistical analysis, to calculate runoff and streamflow or evaluate the characteristics of the storm. Any of these could also be compared between the storm that did occur over the Yahara river and/or the transposed storm that could have occurred over the Yahara.

**Comment by lindsaycarr** [comment]
Thanks! Are there any links we could include to point people to additional resources for where they might continue the analysis?

**Comment by dblodgett-usgs** [comment]
I'm not sure beyond links to the GDP clients and help resources...
