### ISSUE TITLE
Other applications of GDP TEXT

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/how-to-gdp#21]
Add text for this section. See https://github.com/USGS-VIZLAB/how-to-gdp/blob/master/data/page_text.yaml.

**Comment by dblodgett-usgs** [comment]
Here's a start, not sure what else we should cover here.

Results from the GDP can be used for any application that needs input data on a per-polygon basis. Environmental modeling applications as well as data summaries and visualizations can use GDP output with little to no additional processing.

**Comment by lindsaycarr** [comment]
I think we were hoping to include some more specific examples of "environmental modeling applications". So maybe list some projects and link to papers?

**Comment by dblodgett-usgs** [comment]
There's a good list here: https://my.usgs.gov/confluence/display/GeoDataPortal/Featured+Geo+Data+Portal+Applications

We should work on updating that list too!
