### ISSUE TITLE
general text review

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/how-to-gdp#43]
Review and edit the text included in the viz. Note that text additions for #16 #17 #18 and #19 were completed in #40.

**Comment by wdwatkins** [comment]
see google doc in the slack channel

**Comment by lindsaycarr** [comment]
Notes from Roland:
 
- recommend not tying this to climate modeling specifically. it might create an overly limited perception of its utility, and also might be targeted b/c of "climate." I appreciate this language might be a nod to major funders, tho. 
- similar thought is that although the data content may at the moment be regional/national in scale (or just have coarse resolution cells), I would be careful to imply it doesn't do local/fine scale or extent analyses. I think the GDP algorithms are scale-agnostic. 
- "a commonly-used algorithm"?
- as a GISer, I use the "zonal statistics" jargon, as opposed to the "weighted" term. I find the latter less clear b/c one can derive weights on many bases. Maybe "per-feature statistic" would be clearer still? Can appreciate that some of this may be from terms that are established in the GUI.
- would break apart "The GDP will take the gridded dataset and for each timestep, it will average the data within the given spatial extent." Something like "The GDP will derive the average value of a raster for each user-defined feature. If the raster contains multiple time steps, the GDP will derive a per-feature average for each."  
- "timeseries" and "timestep" should be 2 words (each)
- "For each month in the raster temperature data set, there is a grid of data associated with it which is clipped to the spatial feature."
- "...where observations of actual extreme rain events are transposed to different geographic locations..."
- Potter et al citation leads to an article by Hayden et al?
- "In this case, we transpose an extreme storm that impacted Baraboo, WI to assess the response of the Yahara River watershed (near Madison) to the same kind of weather event." (or something)
- don't think you want to say "per-polygon." It's per-feature and a feature maybe multi-polys right?
